// Lumin Icon Registry
// Maps icon names to their Figma node IDs for export/download

export type LuminIconName =
  | "home-13"
  | "home-12"
  | "home-11"
  | "home-10"
  | "home-09"
  | "home-08"
  | "home-07"
  | "home-06"
  | "home-05"
  | "home-04"
  | "home-03"
  | "home-02"
  | "home-01"
  | "resources"
  | "search-01"
  | "search-02"
  | "search-03"
  | "search-04"
  | "search-05"
  | "search-06"
  | "search-07"
  | "search-08"
  | "bookmark"
  | "bookmark-check"
  | "bookmark-remove"
  | "bookmark-plus"
  | "bookmark-minus"
  | "filter-01"
  | "filter-02"
  | "filter-03"
  | "link-01"
  | "link-02"
  | "link-03"
  | "link-04"
  | "link-broken-01"
  | "link-broken-02"
  | "menu-bar-01"
  | "menu-bar-02"
  | "menu-bar-03"
  | "locked-square"
  | "heart-square"
  | "question-square"
  | "dots-square"
  | "minus-square"
  | "plus-square"
  | "block-square"
  | "check-square"
  | "unlocked-03"
  | "locked-03"
  | "unlocked-02"
  | "locked-02"
  | "unlocked-01"
  | "locked-01"
  | "eye"
  | "star"
  | "heart"
  | "question-mark"
  | "dots"
  | "minus"
  | "plus"
  | "block"
  | "check"
  | "share-square"
  | "share-circle"
  | "upload-circle-05"
  | "upload-circle-04"
  | "upload-circle-03"
  | "upload-circle-02"
  | "upload-circle-01"
  | "download-circle-05"
  | "download-circle-04"
  | "download-circle-03"
  | "download-circle-02"
  | "download-circle-01"
  | "locked-circle"
  | "information-circle"
  | "eye-circle"
  | "star-circle"
  | "exclamation-circle"
  | "heart-circle"
  | "question-circle"
  | "dots-circle"
  | "minus-circle"
  | "plus-circle"
  | "block-circle"
  | "check-circle"
  | "log-out-05"
  | "log-out-04"
  | "log-out-03"
  | "log-out-02"
  | "log-out-01"
  | "log-in-05"
  | "log-in-04"
  | "log-in-03"
  | "log-in-02"
  | "log-in-01"
  | "arrow-narrow-down-left"
  | "arrow-narrow-down-right"
  | "arrow-narrow-up-left"
  | "arrow-narrow-up-right"
  | "arrow-narrow-left"
  | "arrow-narrow-right"
  | "arrow-narrow-down"
  | "arrow-narrow-up"
  | "arrow-circle-down-left"
  | "arrow-circle-down-right"
  | "arrow-circle-up-left"
  | "arrow-circle-up-right"
  | "arrow-circle-left"
  | "arrow-circle-right"
  | "arrow-circle-down"
  | "arrow-circle-up"
  | "square-bar-chart-04"
  | "square-bar-chart-03"
  | "square-bar-chart-02"
  | "square-bar-chart-01"
  | "bar-chart-14"
  | "bar-chart-13"
  | "bar-chart-12"
  | "bar-chart-11"
  | "trend-down-01"
  | "trend-up-01"
  | "line-pie-chart-02"
  | "line-pie-chart-01"
  | "line-stacked-down"
  | "line-stacked-up"
  | "line-chart-up-01"
  | "line-chart-down-01"
  | "phone-voice-02"
  | "phone-incoming"
  | "phone-outging"
  | "phone"
  | "message-dots-circle"
  | "message-text-square"
  | "mail-05"
  | "mail-01"
  | "notification-text-circle"
  | "notification-text-square"
  | "bell-05"
  | "bell-01"
  | "announcement-02"
  | "announcement-01"
  | "alert-triangle"
  | "alert-circle"
  | "bank-02"
  | "coins-stacked-03"
  | "currnecy-dollar-circle"
  | "wallet-06"
  | "wallet-05"
  | "credit-card-01"
  | "bank-note-04"
  | "bank-note-03"
  | "invoice"
  | "receipt-04"
  | "receipt-02"
  | "piggy-bank-01"
  | "credit-card-arrow-left"
  | "credit-card-arrow-right"
  | "credit-card-arrow-down"
  | "credit-card-arrow-up"
  | "flash"
  | "image-03"
  | "image-02"
  | "camera-01"
  | "user-circle"
  | "users-03"
  | "users-01"
  | "user-01"
  | "box-archive"
  | "folder-open"
  | "files-01"
  | "file-01"
  | "emergency-light-02"
  | "key-02"
  | "shield-key-hole"
  | "shield-02"
  | "chevron-left"
  | "chevron-right"
  | "chevron-down"
  | "chevron-up"
  | "gear"
  | "headphone-01"
  | "folder-check"
  | "user-minus-01"
  | "user-plus-01"
  | "calendar-check-01"
  | "clock-03"
  | "briefcase-01"
  | "calendar"
  | "clock-02"
  | "briefcase-03"
  | "download-01"
  | "download-02"
  | "download-03"
  | "download-04"
  | "download-circle"
  | "pie-chart-01"
  | "pie-chart-02"
  | "upload-01"
  | "upload-02"
  | "upload-03"
  | "upload-04"
  | "upload-circle"

// Icon registry mapping names to local SVG paths
export const luminIconSrc: Record<LuminIconName, string> = {
  "home-13": "/icons/lumin/home-13.svg",
  "home-12": "/icons/lumin/home-12.svg",
  "home-11": "/icons/lumin/home-11.svg",
  "home-10": "/icons/lumin/home-10.svg",
  "home-09": "/icons/lumin/home-09.svg",
  "home-08": "/icons/lumin/home-08.svg",
  "home-07": "/icons/lumin/home-07.svg",
  "home-06": "/icons/lumin/home-06.svg",
  "home-05": "/icons/lumin/home-05.svg",
  "home-04": "/icons/lumin/home-04.svg",
  "home-03": "/icons/lumin/home-03.svg",
  "home-02": "/icons/lumin/home-02.svg",
  "home-01": "/icons/lumin/home-01.svg",
  "resources": "/icons/lumin/resources.svg",
  "search-01": "/icons/lumin/search-01.svg",
  "search-02": "/icons/lumin/search-02.svg",
  "search-03": "/icons/lumin/search-03.svg",
  "search-04": "/icons/lumin/search-04.svg",
  "search-05": "/icons/lumin/search-05.svg",
  "search-06": "/icons/lumin/search-06.svg",
  "search-07": "/icons/lumin/search-07.svg",
  "search-08": "/icons/lumin/search-08.svg",
  "bookmark": "/icons/lumin/bookmark.svg",
  "bookmark-check": "/icons/lumin/bookmark-check.svg",
  "bookmark-remove": "/icons/lumin/bookmark-remove.svg",
  "bookmark-plus": "/icons/lumin/bookmark-plus.svg",
  "bookmark-minus": "/icons/lumin/bookmark-minus.svg",
  "filter-01": "/icons/lumin/filter-01.svg",
  "filter-02": "/icons/lumin/filter-02.svg",
  "filter-03": "/icons/lumin/filter-03.svg",
  "link-01": "/icons/lumin/link-01.svg",
  "link-02": "/icons/lumin/link-02.svg",
  "link-03": "/icons/lumin/link-03.svg",
  "link-04": "/icons/lumin/link-04.svg",
  "link-broken-01": "/icons/lumin/link-broken-01.svg",
  "link-broken-02": "/icons/lumin/link-broken-02.svg",
  "menu-bar-01": "/icons/lumin/menu-bar-01.svg",
  "menu-bar-02": "/icons/lumin/menu-bar-02.svg",
  "menu-bar-03": "/icons/lumin/menu-bar-03.svg",
  "locked-square": "/icons/lumin/locked-square.svg",
  "heart-square": "/icons/lumin/heart-square.svg",
  "question-square": "/icons/lumin/question-square.svg",
  "dots-square": "/icons/lumin/dots-square.svg",
  "minus-square": "/icons/lumin/minus-square.svg",
  "plus-square": "/icons/lumin/plus-square.svg",
  "block-square": "/icons/lumin/block-square.svg",
  "check-square": "/icons/lumin/check-square.svg",
  "unlocked-03": "/icons/lumin/unlocked-03.svg",
  "locked-03": "/icons/lumin/locked-03.svg",
  "unlocked-02": "/icons/lumin/unlocked-02.svg",
  "locked-02": "/icons/lumin/locked-02.svg",
  "unlocked-01": "/icons/lumin/unlocked-01.svg",
  "locked-01": "/icons/lumin/locked-01.svg",
  "eye": "/icons/lumin/eye.svg",
  "star": "/icons/lumin/star.svg",
  "heart": "/icons/lumin/heart.svg",
  "question-mark": "/icons/lumin/question-mark.svg",
  "dots": "/icons/lumin/dots.svg",
  "minus": "/icons/lumin/minus.svg",
  "plus": "/icons/lumin/plus.svg",
  "block": "/icons/lumin/block.svg",
  "check": "/icons/lumin/check.svg",
  "share-square": "/icons/lumin/share-square.svg",
  "share-circle": "/icons/lumin/share-circle.svg",
  "upload-circle-05": "/icons/lumin/upload-circle-05.svg",
  "upload-circle-04": "/icons/lumin/upload-circle-04.svg",
  "upload-circle-03": "/icons/lumin/upload-circle-03.svg",
  "upload-circle-02": "/icons/lumin/upload-circle-02.svg",
  "upload-circle-01": "/icons/lumin/upload-circle-01.svg",
  "download-circle-05": "/icons/lumin/download-circle-05.svg",
  "download-circle-04": "/icons/lumin/download-circle-04.svg",
  "download-circle-03": "/icons/lumin/download-circle-03.svg",
  "download-circle-02": "/icons/lumin/download-circle-02.svg",
  "download-circle-01": "/icons/lumin/download-circle-01.svg",
  "locked-circle": "/icons/lumin/locked-circle.svg",
  "information-circle": "/icons/lumin/information-circle.svg",
  "eye-circle": "/icons/lumin/eye-circle.svg",
  "star-circle": "/icons/lumin/star-circle.svg",
  "exclamation-circle": "/icons/lumin/exclamation-circle.svg",
  "heart-circle": "/icons/lumin/heart-circle.svg",
  "question-circle": "/icons/lumin/question-circle.svg",
  "dots-circle": "/icons/lumin/dots-circle.svg",
  "minus-circle": "/icons/lumin/minus-circle.svg",
  "plus-circle": "/icons/lumin/plus-circle.svg",
  "block-circle": "/icons/lumin/block-circle.svg",
  "check-circle": "/icons/lumin/check-circle.svg",
  "log-out-05": "/icons/lumin/log-out-05.svg",
  "log-out-04": "/icons/lumin/log-out-04.svg",
  "log-out-03": "/icons/lumin/log-out-03.svg",
  "log-out-02": "/icons/lumin/log-out-02.svg",
  "log-out-01": "/icons/lumin/log-out-01.svg",
  "log-in-05": "/icons/lumin/log-in-05.svg",
  "log-in-04": "/icons/lumin/log-in-04.svg",
  "log-in-03": "/icons/lumin/log-in-03.svg",
  "log-in-02": "/icons/lumin/log-in-02.svg",
  "log-in-01": "/icons/lumin/log-in-01.svg",
  "arrow-narrow-down-left": "/icons/lumin/arrow-narrow-down-left.svg",
  "arrow-narrow-down-right": "/icons/lumin/arrow-narrow-down-right.svg",
  "arrow-narrow-up-left": "/icons/lumin/arrow-narrow-up-left.svg",
  "arrow-narrow-up-right": "/icons/lumin/arrow-narrow-up-right.svg",
  "arrow-narrow-left": "/icons/lumin/arrow-narrow-left.svg",
  "arrow-narrow-right": "/icons/lumin/arrow-narrow-right.svg",
  "arrow-narrow-down": "/icons/lumin/arrow-narrow-down.svg",
  "arrow-narrow-up": "/icons/lumin/arrow-narrow-up.svg",
  "arrow-circle-down-left": "/icons/lumin/arrow-circle-down-left.svg",
  "arrow-circle-down-right": "/icons/lumin/arrow-circle-down-right.svg",
  "arrow-circle-up-left": "/icons/lumin/arrow-circle-up-left.svg",
  "arrow-circle-up-right": "/icons/lumin/arrow-circle-up-right.svg",
  "arrow-circle-left": "/icons/lumin/arrow-circle-left.svg",
  "arrow-circle-right": "/icons/lumin/arrow-circle-right.svg",
  "arrow-circle-down": "/icons/lumin/arrow-circle-down.svg",
  "arrow-circle-up": "/icons/lumin/arrow-circle-up.svg",
  "square-bar-chart-04": "/icons/lumin/square-bar-chart-04.svg",
  "square-bar-chart-03": "/icons/lumin/square-bar-chart-03.svg",
  "square-bar-chart-02": "/icons/lumin/square-bar-chart-02.svg",
  "square-bar-chart-01": "/icons/lumin/square-bar-chart-01.svg",
  "bar-chart-14": "/icons/lumin/bar-chart-14.svg",
  "bar-chart-13": "/icons/lumin/bar-chart-13.svg",
  "bar-chart-12": "/icons/lumin/bar-chart-12.svg",
  "bar-chart-11": "/icons/lumin/bar-chart-11.svg",
  "trend-down-01": "/icons/lumin/trend-down-01.svg",
  "trend-up-01": "/icons/lumin/trend-up-01.svg",
  "line-pie-chart-02": "/icons/lumin/line-pie-chart-02.svg",
  "line-pie-chart-01": "/icons/lumin/line-pie-chart-01.svg",
  "line-stacked-down": "/icons/lumin/line-stacked-down.svg",
  "line-stacked-up": "/icons/lumin/line-stacked-up.svg",
  "line-chart-up-01": "/icons/lumin/line-chart-up-01.svg",
  "line-chart-down-01": "/icons/lumin/line-chart-down-01.svg",
  "phone-voice-02": "/icons/lumin/phone-voice-02.svg",
  "phone-incoming": "/icons/lumin/phone-incoming.svg",
  "phone-outging": "/icons/lumin/phone-outging.svg",
  "phone": "/icons/lumin/phone.svg",
  "message-dots-circle": "/icons/lumin/message-dots-circle.svg",
  "message-text-square": "/icons/lumin/message-text-square.svg",
  "mail-05": "/icons/lumin/mail-05.svg",
  "mail-01": "/icons/lumin/mail-01.svg",
  "notification-text-circle": "/icons/lumin/notification-text-circle.svg",
  "notification-text-square": "/icons/lumin/notification-text-square.svg",
  "bell-05": "/icons/lumin/bell-05.svg",
  "bell-01": "/icons/lumin/bell-01.svg",
  "announcement-02": "/icons/lumin/announcement-02.svg",
  "announcement-01": "/icons/lumin/announcement-01.svg",
  "alert-triangle": "/icons/lumin/alert-triangle.svg",
  "alert-circle": "/icons/lumin/alert-circle.svg",
  "bank-02": "/icons/lumin/bank-02.svg",
  "coins-stacked-03": "/icons/lumin/coins-stacked-03.svg",
  "currnecy-dollar-circle": "/icons/lumin/currnecy-dollar-circle.svg",
  "wallet-06": "/icons/lumin/wallet-06.svg",
  "wallet-05": "/icons/lumin/wallet-05.svg",
  "credit-card-01": "/icons/lumin/credit-card-01.svg",
  "bank-note-04": "/icons/lumin/bank-note-04.svg",
  "bank-note-03": "/icons/lumin/bank-note-03.svg",
  "invoice": "/icons/lumin/invoice.svg",
  "receipt-04": "/icons/lumin/receipt-04.svg",
  "receipt-02": "/icons/lumin/receipt-02.svg",
  "piggy-bank-01": "/icons/lumin/piggy-bank-01.svg",
  "credit-card-arrow-left": "/icons/lumin/credit-card-arrow-left.svg",
  "credit-card-arrow-right": "/icons/lumin/credit-card-arrow-right.svg",
  "credit-card-arrow-down": "/icons/lumin/credit-card-arrow-down.svg",
  "credit-card-arrow-up": "/icons/lumin/credit-card-arrow-up.svg",
  "flash": "/icons/lumin/flash.svg",
  "image-03": "/icons/lumin/image-03.svg",
  "image-02": "/icons/lumin/image-02.svg",
  "camera-01": "/icons/lumin/camera-01.svg",
  "user-circle": "/icons/lumin/user-circle.svg",
  "users-03": "/icons/lumin/users-03.svg",
  "users-01": "/icons/lumin/users-01.svg",
  "user-01": "/icons/lumin/user-01.svg",
  "box-archive": "/icons/lumin/box-archive.svg",
  "folder-open": "/icons/lumin/folder-open.svg",
  "files-01": "/icons/lumin/files-01.svg",
  "file-01": "/icons/lumin/file-01.svg",
  "emergency-light-02": "/icons/lumin/emergency-light-02.svg",
  "key-02": "/icons/lumin/key-02.svg",
  "shield-key-hole": "/icons/lumin/shield-key-hole.svg",
  "shield-02": "/icons/lumin/shield-02.svg",
  "chevron-left": "/icons/lumin/chevron-left.svg",
  "chevron-right": "/icons/lumin/chevron-right.svg",
  "chevron-down": "/icons/lumin/chevron-down.svg",
  "chevron-up": "/icons/lumin/chevron-up.svg",
  "gear": "/icons/lumin/gear.svg",
  "headphone-01": "/icons/lumin/headphone-01.svg",
  "folder-check": "/icons/lumin/folder-check.svg",
  "user-minus-01": "/icons/lumin/user-minus-01.svg",
  "user-plus-01": "/icons/lumin/user-plus-01.svg",
  "calendar-check-01": "/icons/lumin/calendar-check-01.svg",
  "clock-03": "/icons/lumin/clock-03.svg",
  "briefcase-01": "/icons/lumin/briefcase-01.svg",
  "calendar": "/icons/lumin/calendar.svg",
  "clock-02": "/icons/lumin/clock-02.svg",
  "briefcase-03": "/icons/lumin/briefcase-03.svg",
  "download-01": "/icons/lumin/download-01.svg",
  "download-02": "/icons/lumin/download-02.svg",
  "download-03": "/icons/lumin/download-03.svg",
  "download-04": "/icons/lumin/download-04.svg",
  "download-circle": "/icons/lumin/download-circle.svg",
  "pie-chart-01": "/icons/lumin/pie-chart-01.svg",
  "pie-chart-02": "/icons/lumin/pie-chart-02.svg",
  "upload-01": "/icons/lumin/upload-01.svg",
  "upload-02": "/icons/lumin/upload-02.svg",
  "upload-03": "/icons/lumin/upload-03.svg",
  "upload-04": "/icons/lumin/upload-04.svg",
  "upload-circle": "/icons/lumin/upload-circle.svg",
} as const

// Get all icon names as an array
export const allIconNames = Object.keys(luminIconSrc) as LuminIconName[]

